### ISSUE TITLE
Mod Doesn't Work on SpongeForge Servers

### ISSUE THREAD

**Issue by tyler489** [Daomephsta/LootTweaker#19]
Playing the FOOLCRAFT modpack and i noticed my withers wern't droping the correct lootbags and netherstars they were supposed to.. did some digging and they work fine in a regular forge Server and in Sp i'm guessing this is a spongeforge issue and i'm going to report it there aswell

**Comment by Leviathan143** [comment]
Sounds like Sponge isn't firing the LootTableLoadEvent. LootTweaker depends on this event to work, there is no other way to modify loot tables. I'll have a look this weekend and see what's going on.

**Comment by Leviathan143** [comment]
@tyler489 Does this bug still occur?

**Comment by Leviathan143** [comment]
I'll take that as a no

**Comment by tyler489** [comment]
Dont know we shut down the modpack a while ago

**Comment by Leviathan143** [comment]
@tyler489 In cases like that, the issue should stay open, as it may still exist. I'll do some testing myself if I can.

**Comment by Time6628** [comment]
Running the same modpack with SpongeForge and the latest version causes this crash on startup. https://gist.github.com/Time6628/57557fb8a3e665571a7dfc8f34032059

**Comment by Leviathan143** [comment]
@Time6628 Do not hijack another issue just because it is vaguely similar to yours. Create a new issue.

**Comment by Daomephsta** [comment]
2 years late, but better late than never. Finally got around to testing this out myself. SpongeForge servers work fine with LootTweaker.

**Comment by zediious** [comment]
I'm having this issue myself, I have not performed tests with bare-bones mods just yet, but it seems not having Sponge installed allows chests to populate on servers.

I have more information regarding the issue on my pack's repo [here](https://github.com/ShadowRaptorMC/galacticdrive/issues/19)
