### ISSUE TITLE
[Request] Creating new loot tables

### ISSUE THREAD

**Issue by belathus** [Daomephsta/LootTweaker#34]
I'm trying to add a new empty loot table to the modpack so I can add drops to mobs in an EvilCraft spirit furnace that don't currently use loot tables for their drops (IE: Animania).

For reference, I'm still running 1.10.2.

The relevant section of EvilCraft's config is linked here: https://github.com/belathus/Wanderlust-Renewed/blob/master/config/evilcraft.cfg#L447-L449

**Comment by Leviathan143** [comment]
Already on the to-do list

**Comment by Leviathan143** [comment]
I tried to implement this the other day, it looks like it's not possible in 1.12. I had a look at the 1.13 loot system code by decompiling a snapshot, it looks like this may be viable in 1.13. It's hard to tell as the obfuscation makes the decompiled code hard to read.

**Comment by xt9** [comment]
Couldn't you just do what ContentTweaker does and use a loader to support adding new loottables early in preinit, so they exist later when you alter it with loottweaker.

for example
`// load script early with "#loader loottweaker"`
`CraftTweakerAPI.tweaker.loadScript(false, LootTweakerMain.Constants.MODID);`
called during preinit

**Comment by Leviathan143** [comment]
@xt9 
> Couldn't you just do what ContentTweaker does and use a loader to support adding new loottables early in preinit, so they exist later when you try to alter it with loottweaker.

No, the issue is with where MC 1.12 loads loot tables from, it has nothing to do with the loading stage,

**Comment by Daomephsta** [comment]
There's a test release for this now, if either of you are interested in testing it.
https://github.com/Daomephsta/LootTweaker/releases/tag/create-table-pre1

**Comment by Daomephsta** [comment]
Available in 0.2.0, at long last!
https://www.curseforge.com/minecraft/mc-mods/loottweaker/files/2988990
