### ISSUE TITLE
Where do I put the damn code?

### ISSUE THREAD

**Issue by NineDivinez** [Daomephsta/LootTweaker#46]
Your tutorials are great, I have the code written up, but... where the fuck do I put it?  I'm trying to add paper to mob drops to give out Stargate Addresses for my private server, but the files your tutorials say to open don't exist...  What am I doing wrong?

**Comment by Daomephsta** [comment]
I don't know, since you've told me barely anything about what you actually did. 
I suspect fixing this will require a longish conversation, so join [my Discord server](http://discord.gg/Gut3sdX). Conducting long conversations in a GitHub issue is painful.

**Comment by NineDivinez** [comment]
I've told you everything except I installed the mod.  But alright, I'll join the server.

**Comment by Daomephsta** [comment]
Resolved via Discord
