### ISSUE TITLE
crash when using /help command

### ISSUE THREAD

**Issue by vibes81** [Daomephsta/LootTweaker#48]
Please fill out all applicable sections in the template below:

Crash when using help command

use the /help

**Version Info (Exact versions only):**  
LootTweaker:  1.12.2-0.0.8
CraftTweaker/Minetweaker:  12.2-4.1.13
Forge:  14.23.5.2775
Minecraft:  12.2.2

https://paste.dimdev.org/ecudafaluq.mccrash

**Comment by Daomephsta** [comment]
Alright, I'll have a look at this later. Pretty sure it's on someone else's end since nothing should be null there. I think some other mod's help additions are broken.
