### ISSUE TITLE
Add server-side only installation capability

### ISSUE THREAD

**Issue by callmesabs** [Daomephsta/LootTweaker#50]
Server administrator users may have items that they want to remove from a server, but don't want to require every player to modify their mod pack files.  Since the items can be removed from the loot tables on the server, it would stop people from obtaining them.

Additionally, there are a number of other mods that allow server-side installation where a client-side adds more functionality (like for server admins).

Per our Discord conversation, 
[12:19 PM] Leviathan: It looks like commands can be either clientside or serverside, they're not both.
[12:19 PM] Leviathan: Which means I just need to set a particular flag so that Forge will allow serverside only installation.

**Comment by Daomephsta** [comment]
After investigating this is not possible, as CraftTweaker 2 cannot be installed server-side only. This appears to be a deliberate choice.

**Comment by Daomephsta** [comment]
I realised this is actually possible. LootTweaker now supports server-only installation, starting with 0.1.7.
See the FAQ on the CurseForge page for details.
