### ISSUE TITLE
Help with LootTweaker

### ISSUE THREAD

**Issue by TheAnubisGod** [Daomephsta/LootTweaker#54]
Please fill out all applicable sections in the template below:

**Description:**
I need help) I cant find problem.

**Version Info (Exact versions only):**  
LootTweaker:  0.0.10
CraftTweaker/Minetweaker:  4.1.19
Forge:  14.23.5.2838
Minecraft:  1.12.2

**Logs, scripts and other useful information:**  
import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Conditions;
import loottweaker.vanilla.loot.Functions;

val simpleDungeon = LootTables.getTable("minecraft:chests/simple_dungeon");
val abandonedMineshaft = LootTables.getTable("minecraft:chests/abandoned_mineshaft");
val desertPyramid = LootTables.getTable("minecraft:chests/desert_pyramid");
val endCityTreasure = LootTables.getTable("minecraft:chests/end_city_treasure");
val iglooChest = LootTables.getTable("minecraft:chests/igloo_chest");
val jungleTemple = LootTables.getTable("minecraft:chests/jungle_temple);
val jungleTempleDispenser = LootTables.getTable("minecraft:chests/jungle_temple_dispenser");
val netherBridge = LootTables.getTable("minecraft:chests/nether_bridge");
val villageBlacksmith = LootTables.getTable("minecraft:chests/village_blacksmith");
val woodlandMansion = LootTables.getTable("minecraft:chests/woodland_mansion");

simpleDungeon.removePool("Ender IO");
abandonedMineshaft.removePool("Ender IO");
desertPyramid.removePool("Ender IO");
endCityTreasure.removePool("Ender IO");
iglooChest.removePool("Ender IO");
jungleTemple.removePool("Ender IO");
jungleTempleDispenser.removePool("Ender IO");
netherBridge.removePool("Ender IO");
villageBlacksmith.removePool("Ender IO");
woodlandMansion.removePool("Ender IO");

**Comment by Daomephsta** [comment]
I need more information than this, I cannot help you with just a script. Tell me what you expected to happen, and what actually happened.

**Comment by Daomephsta** [comment]
It's been 2 weeks with no more information, so I'm closing this.
